### ISSUE TITLE
"MangaRipper has stopped working"

### ISSUE THREAD

**Issue by iYatsumi** [NguyenDanPhuong/MangaRipper#33]
whenever i try to download any manga, i get this error the minute i click on start download. 
The app was working fine a few weeks earlier, i don't if it was due to something i did on my pc or anything but i am unable to use the app to download any mangas. 

[https://gyazo.com/e8b6dcdf832d7a7ca8ecd8425a820825](url)

**Comment by JedBurke** [comment]
I'm not getting any errors with that series on Windows 8. Was the whitespace 'directory' between "Desktop" and "Relife" there when it last worked?

Check in "%APPDATA%\MangaRipper\Logs" for a text file with  the date when it last failed download and upload it please.

**Comment by iYatsumi** [comment]
i dont know what was the error but the new release fine and looks great ! so nvm ~ and yes the empty space was there its the name of my folder.  and as for the log it looked something like this for future references.

2017-01-18 19:38:00.9869 INFO > Framework.Init() 
2017-01-18 19:38:01.0807 INFO > Worker() 
2017-01-18 19:38:07.0507 INFO > FindChapters: http://mangafox.me/manga/blood_lad/ 
2017-01-18 19:38:07.2069 INFO > DownloadStringAsync: http://mangafox.me/manga/blood_lad/ 
2017-01-18 19:38:07.9881 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-18 19:38:11.7002 INFO > FindChapters: http://mangafox.me/manga/days/ 
2017-01-18 19:38:11.7158 INFO > DownloadStringAsync: http://mangafox.me/manga/days/ 
2017-01-18 19:38:12.0596 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-18 19:38:21.3053 INFO > FindChapters: http://mangafox.me/manga/relife 
2017-01-18 19:38:21.3208 INFO > DownloadStringAsync: http://mangafox.me/manga/relife 
2017-01-18 19:38:21.8678 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-18 19:38:36.2806 INFO > DownloadChapter: http://mangafox.me/manga/relife/c160/1.html To: C:\Users\Anh-Tai\Desktop\                \Relife 
2017-01-18 19:38:36.4524 INFO > DownloadStringAsync: http://mangafox.me/manga/relife/c160/1.html 
2017-01-18 19:38:37.1087 INFO > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-18 19:38:37.1399 INFO > DownloadStringAsync - Total: 0 
2017-01-18 19:38:37.1556 INFO > Parse: <img src="(?<Value>[^"]+)"[ ]+width= 
2017-01-18 19:38:37.2181 INFO > DownloadChapter: http://mangafox.me/manga/relife/c161/1.html To: C:\Users\Anh-Tai\Desktop\                \Relife 
2017-01-18 19:38:37.2337 INFO > DownloadStringAsync: http://mangafox.me/manga/relife/c161/1.html 
2017-01-18 19:38:47.1326 INFO > Framework.Init() 
2017-01-18 19:38:47.2263 INFO > Worker() 
2017-01-18 19:38:51.8061 INFO > FindChapters: http://mangafox.me/manga/relife 
2017-01-18 19:38:51.8998 INFO > DownloadStringAsync: http://mangafox.me/manga/relife 
2017-01-18 19:38:52.7443 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-18 19:39:07.4678 INFO > DownloadChapter: http://mangafox.me/manga/relife/c160/1.html To: C:\Users\Anh-Tai\Desktop\                \Days 
2017-01-18 19:39:07.5147 INFO > DownloadStringAsync: http://mangafox.me/manga/relife/c160/1.html 
2017-01-18 19:39:08.1553 INFO > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-18 19:39:08.1866 INFO > DownloadStringAsync - Total: 0 
2017-01-18 19:39:08.2022 INFO > Parse: <img src="(?<Value>[^"]+)"[ ]+width= 
2017-01-18 19:39:08.2647 INFO > DownloadChapter: http://mangafox.me/manga/relife/c161/1.html To: C:\Users\Anh-Tai\Desktop\                \Days 
2017-01-18 19:39:08.2803 INFO > DownloadStringAsync: http://mangafox.me/manga/relife/c161/1.html 
2017-01-18 19:39:28.3678 INFO > Framework.Init() 
2017-01-18 19:39:28.4671 INFO > Worker() 
2017-01-18 19:41:53.3481 INFO > Framework.Init() 
2017-01-18 19:41:53.4262 INFO > Worker() 
2017-01-18 19:41:53.8464 ERROR System.IO.FileNotFoundException: Could not find file 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'.
File name: 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at MangaRipper.Common.LoadDownloadTasks(String fileName) in C:\projects\mangaripper\MangaRipper\Helper\Common.cs:line 61 
System.IO.FileNotFoundException: Could not find file 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'.
File name: 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at MangaRipper.Common.LoadDownloadTasks(String fileName) in C:\projects\mangaripper\MangaRipper\Helper\Common.cs:line 61
2017-01-18 19:42:06.7072 INFO > FindChapters: http://mangafox.me/manga/relife 
2017-01-18 19:42:06.7540 INFO > DownloadStringAsync: http://mangafox.me/manga/relife 
2017-01-18 19:42:07.5353 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-18 19:42:36.1844 INFO > DownloadChapter: http://mangafox.me/manga/relife/c160/1.html To: C:\Users\Anh-Tai\Documents 
2017-01-18 19:42:36.2469 INFO > DownloadStringAsync: http://mangafox.me/manga/relife/c160/1.html 
2017-01-18 19:42:36.9192 INFO > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-18 19:42:36.9349 INFO > DownloadStringAsync - Total: 0 
2017-01-18 19:42:36.9505 INFO > Parse: <img src="(?<Value>[^"]+)"[ ]+width= 
2017-01-18 19:42:37.0286 INFO > DownloadChapter: http://mangafox.me/manga/relife/c161/1.html To: C:\Users\Anh-Tai\Documents 
2017-01-18 19:42:37.0442 INFO > DownloadStringAsync: http://mangafox.me/manga/relife/c161/1.html 
2017-01-18 19:43:06.6339 INFO > Framework.Init() 
2017-01-18 19:43:06.7276 INFO > Worker() 
2017-01-18 19:43:07.1991 ERROR System.IO.FileNotFoundException: Could not find file 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'.
File name: 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at MangaRipper.Common.LoadDownloadTasks(String fileName) in C:\projects\mangaripper\MangaRipper\Helper\Common.cs:line 61 
System.IO.FileNotFoundException: Could not find file 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'.
File name: 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at MangaRipper.Common.LoadDownloadTasks(String fileName) in C:\projects\mangaripper\MangaRipper\Helper\Common.cs:line 61
2017-01-18 19:43:13.4477 INFO > FindChapters: http://mangafox.me/manga/relife 
2017-01-18 19:43:13.5102 INFO > DownloadStringAsync: http://mangafox.me/manga/relife 
2017-01-18 19:43:14.2915 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-18 19:43:29.6388 INFO > DownloadChapter: http://mangafox.me/manga/relife/c162/1.html To: C:\Users\Anh-Tai\Documents 
2017-01-18 19:43:29.7013 INFO > DownloadStringAsync: http://mangafox.me/manga/relife/c162/1.html 
2017-01-18 19:43:30.3445 INFO > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-18 19:43:30.3757 INFO > DownloadStringAsync - Total: 0 
2017-01-18 19:43:30.3913 INFO > Parse: <img src="(?<Value>[^"]+)"[ ]+width= 
2017-01-18 19:47:21.5156 INFO > Framework.Init() 
2017-01-18 19:47:21.6039 INFO > Worker() 
2017-01-18 19:47:21.9789 ERROR System.IO.FileNotFoundException: Could not find file 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'.
File name: 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at MangaRipper.Common.LoadDownloadTasks(String fileName) in C:\projects\mangaripper\MangaRipper\Helper\Common.cs:line 61 
System.IO.FileNotFoundException: Could not find file 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'.
File name: 'C:\Users\Anh-Tai\AppData\Roaming\NguyenDanPhuong\MangaRipper\1.0.140\IChapterCollection.bin'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at MangaRipper.Common.LoadDownloadTasks(String fileName) in C:\projects\mangaripper\MangaRipper\Helper\Common.cs:line 61
2017-01-18 19:48:11.0072 INFO > Framework.Init() 
2017-01-18 19:48:11.1208 INFO > Worker() 
2017-01-18 19:48:41.3206 INFO > FindChapters: http://mangafox.me/manga/days/ 
2017-01-18 19:48:41.3675 INFO > DownloadStringAsync: http://mangafox.me/manga/days/ 
2017-01-18 19:48:41.8843 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-18 19:49:03.5843 INFO > DownloadChapter: http://mangafox.me/manga/days/v10/c083/1.html To: C:\Users\Anh-Tai\Documents 
2017-01-18 19:49:03.6468 INFO > DownloadStringAsync: http://mangafox.me/manga/days/v10/c083/1.html 
2017-01-18 19:49:04.2722 INFO > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-18 19:49:04.3035 INFO > DownloadStringAsync - Total: 0 
2017-01-18 19:49:04.3191 INFO > Parse: <img src="(?<Value>[^"]+)"[ ]+width= 
2017-01-18 22:05:26.6402 INFO > Framework.Init() 
2017-01-18 22:05:26.7809 INFO > Worker() 
2017-01-18 22:05:40.0161 INFO > Framework.Init() 
2017-01-18 22:05:40.0942 INFO > Worker() 
2017-01-18 22:06:00.7181 INFO > FindChapters: http://mangafox.me/manga/relife 
2017-01-18 22:06:00.7650 INFO > DownloadStringAsync: http://mangafox.me/manga/relife 
2017-01-18 22:06:01.6243 INFO > ParseGroup: <a href="(?<Value>[^"]+)" title="(|[^"]+)" class="tips">(?<Name>[^<]+)</a> 
2017-01-18 22:07:15.3119 INFO > DownloadChapter: http://mangafox.me/manga/relife/c162/ To: C:\Users\Anh-Tai\Desktop\                \Relife 
2017-01-18 22:07:15.4213 INFO > DownloadStringAsync: http://mangafox.me/manga/relife/c162/ 
2017-01-18 22:07:19.1730 INFO > Parse: <option value="(?<Value>[^"]+)" (|selected="selected")>\d+</option> 
2017-01-18 22:07:19.2043 INFO > DownloadStringAsync - Total: 0 
2017-01-18 22:07:19.2199 INFO > Parse: <img src="(?<Value>[^"]+)"[ ]+width=

**Comment by iYatsumi** [comment]
the same error just happened with the newest released and for some reason every time it crashes, it removes all my bookmarks as well. 

https://gyazo.com/1835175c11abc4178f72bc16227c832b

the log: 
https://gyazo.com/404182d089e0886639dcde5a8d61d50b

**Comment by iYatsumi** [comment]
So the error seems to be on the server or website that im using to download the manga, i tried re downloading it from Bato but that didnt work either, however, it was successful when i tried to download it from Mangareader.net

**Comment by NguyenDanPhuong** [comment]
@iYatsumi: I can download it normally. But I think maybe you're living in a country where that manga is licensed and MangaFox and Batoto block your access.

The error message is not good and I will improve it. Thank you for reporting :)

**Comment by JedBurke** [comment]
[ReLIFE](http://www.mangaupdates.com/series.html?id=113469) has indeed been licensed. But since the blocking seems spotty, I'd like to know whether MangaRipper or the host is at fault. Can you read those chapters from your web browser or are you blocked completely?

**Comment by iYatsumi** [comment]
i can read them fine on browsers, i already had a few chapters downloaded before from mangafox with that manga.

**Comment by NguyenDanPhuong** [comment]
The crash bug fixed in latest version. Can you use it and reupload logs file in a here? I've added more detailed logging.

**Comment by iYatsumi** [comment]
https://gyazo.com/95a720b7e3f1a4024a0b0db771fada7f

Works fine indeed

**Comment by NguyenDanPhuong** [comment]
Ok. I think I've found the problem. :) MangaFox returns error when you made too many connections to their server in a short time. You may have run 2 instance of MangaRipper to download from MangaFox or download and browsing MangaFox at the same time.

**Comment by iYatsumi** [comment]
i don't recall having more than one connection to the server though, i only had the app open without my browers on mangafox. But since the problem was resolve, it's all good.
