### ISSUE TITLE
MangaRipper has stop working

### ISSUE THREAD

**Issue by binhminh86** [NguyenDanPhuong/MangaRipper#50]
i download and extract the zip file.
then try to run MangaRipper.exe but it not working.
windows 7, already got the .net framework 4 cllient profile
![image](https://cloud.githubusercontent.com/assets/10412394/23176211/ba545468-f894-11e6-9d41-2fc99cd0a48b.png)

**Comment by JedBurke** [comment]
Did you extract *all* of the files and folders from the zip file before running?

**Comment by binhminh86** [comment]
Yes all in one folder

**Comment by JedBurke** [comment]
All right. Check if the application is not being blocked by your firewall. On startup, it checks for updates but will crash if blocked. The error message may be different depending on the version of Windows.

If the problem still persists, please upload the text file with the most recent date in the *%APPDATA%\MangaRipper\Logs* folder.

**Comment by binhminh86** [comment]
Sorry for late reply
I always disable firewall in my computers.
here is my log


2017-02-22 00:23:14.2863 INFO > Main() 
2017-02-22 00:23:14.3173 INFO > Framework.Init() 
2017-02-22 00:23:14.3173 INFO > Worker() 
2017-02-22 00:23:14.3173 FATAL Unhandled Exception 
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\Truong\Downloads\MangaRipper (1)\Plugins\MangaRipper.Plugin.Batoto.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\Truong\Downloads\MangaRipper (1)\Plugins\MangaRipper.Plugin.Batoto.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at MangaRipper.Core.Services.PluginService.LoadPluginAssemblies(String path) in C:\projects\mangaripper\MangaRipper.Core\Services\PluginService.cs:line 43
   at MangaRipper.Core.Services.PluginService.LoadWebPlugins(String path) in C:\projects\mangaripper\MangaRipper.Core\Services\PluginService.cs:line 24
   at MangaRipper.Core.Providers.FrameworkProvider.Init(String pluginPath) in C:\projects\mangaripper\MangaRipper.Core\Providers\FrameworkProvider.cs:line 32
   at MangaRipper.Program.Main() in C:\projects\mangaripper\MangaRipper\Program.cs:line 22

**Comment by NguyenDanPhuong** [comment]
The problem looks similar to the one in F.A.Q. (https://github.com/NguyenDanPhuong/MangaRipper/wiki/F.A.Q.)

Can you run PowerShell as mentioned: Dir "<Path to MangaRipper folder>" -Recurse | Unblock-File

**Comment by binhminh86** [comment]
This powershell ? sorry i do not have much knowledge in this.
![image](https://cloud.githubusercontent.com/assets/10412394/23336802/b8d5ab20-fc0c-11e6-9b23-c106d74a1c7c.png)

**Comment by NguyenDanPhuong** [comment]
It's seem your PowerShell version is an old version. Another way to work around this is use 7-Zip to extract MangaRipper.zip file. Don't use build-in un-zip or WinRAR. 7-Zip can be downloaded from http://7-zip.org/

**Comment by JedBurke** [comment]
As @NguyenDanPhuong mentioned, the file(s) may be blocked.

Besides with Poweshell, you may also identify that the file has been blocked by right-clicking it in Explorer and clicking Properties. Here's an image from The Windows Club of how a blocked file appears in the Properties window.

http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2012/05/File-Originated-From-Internet-313x400.png

The entire MangaRipper zip file may be blocked, so first check that. If it appears as it does in the above image, click 'Unblock' and 'Apply'. Finally re-extract the files. 

Since the log specifically mentions it, check 'Plugins\MangaRipper.Plugin.Batoto.dll'. The DLL itself may be blocked while the zip file isn't.

[The Windows Club article](http://www.thewindowsclub.com/file-is-locked-windows)

**Comment by binhminh86** [comment]
Thanks you guys so much, did as @JedBurke suggest and now it work!!
